### ISSUE TITLE
Merging with Objc_tools

### ISSUE THREAD

**Issue by scj643** [mogira/MP4Pythonista#1]
I've been working on a major library for pythonista and objc. If you want take a look at https://github.com/scj643/objc_tools

**Comment by mogira** [comment]
Thank you for your information. I'm modifying to use your objc_tools library. This is so useful, thanks: )
May I create a pull request to your objc_tools to merge 'getNowPlayingQueue' function in MPUtils.py?

**Comment by scj643** [comment]
Yes please do
